apiVersion: v1
kind: Service
metadata:
  labels:
    app: retro-synthesis-v2
  name: retro-synthesis-v2
  namespace: launching-workload-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8050
      protocol: TCP
      targetPort: 8050
      name: dash
  selector:
    app: retro-synthesis-v2
  sessionAffinity: None
  type: ClusterIP
